import fs from "node:fs/promises";
import path from "node:path";
import { randomUUID } from "node:crypto";
import { NextResponse } from "next/server";
import { buildMediaManifest,parseDeck,readOutline } from "@/lib/parser";
import { projectDir,publicProject,saveProject,saveWorkflowArtifacts } from "@/lib/store";
import { ensureProjectThumbnails } from "@/lib/thumbnails";
import type { Project } from "@/lib/types";
export const runtime="nodejs";

export async function POST(req:Request){try{const form=await req.formData(),deck=form.get("deck"),outline=form.get("outline");if(!(deck instanceof File)||!(outline instanceof File))return NextResponse.json({error:"请上传课件和课纲。"},{status:400});const id=randomUUID(),dir=await projectDir(id),deckExt=path.extname(deck.name).toLowerCase(),outlineExt=path.extname(outline.name).toLowerCase();let sourcePath=path.join(dir,`source${deckExt}`),sourceExt=deckExt;await fs.writeFile(sourcePath,Buffer.from(await deck.arrayBuffer()));if(deckExt===".zip"){const JSZip=(await import("jszip")).default,zip=await JSZip.loadAsync(await fs.readFile(sourcePath)),root=path.join(dir,"deck");for(const [name,item] of Object.entries(zip.files)){if(item.dir||isArchiveJunk(name)||name.includes("..")||path.isAbsolute(name))continue;const target=path.join(root,name);await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,await item.async("nodebuffer"));}const htmls=(await walk(root)).filter(f=>/\.html?$/i.test(f)&&!isArchiveJunk(path.relative(root,f)));if(!htmls.length)throw new Error("ZIP 中没有找到可用的 HTML 课件。请确认压缩包包含主 HTML 文件。");sourcePath=(await chooseMainHtml(htmls));sourceExt=path.extname(sourcePath).toLowerCase();const missing=await missingLocalAssets(sourcePath);if(missing.length)throw new Error(`ZIP 不完整：主 HTML 引用了 ${missing.length} 个未打包资源，例如 ${missing.slice(0,3).join("、")}。请将 HTML 与 assets 文件夹一起重新压缩上传。`);}const outlinePath=path.join(dir,"outline.txt"),outlineText=await readOutline(await saveTemp(dir,outline,outlineExt),outlineExt);await fs.writeFile(outlinePath,outlineText,"utf8");const slides=await parseDeck(sourcePath,sourceExt),mediaManifest=await buildMediaManifest(sourcePath,slides);const project:Project={id,title:String(form.get("title")||"")||slides[0]?.title||deck.name,sourceType:sourceExt.slice(1),sourcePath,sourceFile:path.basename(sourcePath),outlinePath,status:"parsed",audience:String(form.get("audience")||"高校学生"),targetMinutes:Number(form.get("duration")||40),style:String(form.get("style")||"平静的大学讲师"),createdAt:new Date().toISOString(),slides,mediaManifest};await ensureProjectThumbnails(project);await saveProject(project);await saveWorkflowArtifacts(project);return NextResponse.json(publicProject(project));}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"课件解析失败"},{status:500})}}
async function saveTemp(dir:string,file:File,ext:string){const p=path.join(dir,`outline-source${ext}`);await fs.writeFile(p,Buffer.from(await file.arrayBuffer()));return p;}
async function walk(dir:string):Promise<string[]>{return (await Promise.all((await fs.readdir(dir,{withFileTypes:true})).map(x=>x.isDirectory()?walk(path.join(dir,x.name)):path.join(dir,x.name)))).flat();}
function isArchiveJunk(name:string){return name.split(/[\\/]/).some(part=>part==="__MACOSX"||part===".DS_Store"||part.startsWith("._"))}
async function chooseMainHtml(files:string[]){const scored=await Promise.all(files.map(async file=>{const stat=await fs.stat(file),name=path.basename(file).toLowerCase();return {file,score:(/^(index|课件|slides?|deck|presentation)\.html?$/.test(name)?1_000_000:0)+stat.size}}));return scored.sort((a,b)=>b.score-a.score)[0].file}
async function missingLocalAssets(htmlPath:string){const {load}=await import("cheerio"),$=load(await fs.readFile(htmlPath,"utf8")),references=new Set<string>();$("img[src],video[src],audio[src],source[src],link[href],script[src]").each((_,element)=>{const value=$(element).attr("src")||$(element).attr("href");if(value&&!value.startsWith("data:")&&!value.startsWith("#")&&!/^https?:/i.test(value))references.add(decodeURIComponent(value.split(/[?#]/)[0]))});const missing:string[]=[];for(const reference of references){try{await fs.access(path.resolve(path.dirname(htmlPath),reference))}catch{missing.push(reference)}}return missing}
