"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { ArrowRight, BookOpenText, CaretDown, CaretLeft, CaretRight, Check, DownloadSimple, FileHtml, FileText, FilmSlate, Pause, Play, Sparkle, Waveform, X } from "@phosphor-icons/react";

type Slide={page:number;title:string;text:string;type:string;narration?:string;audioPrompt?:string;voiceoverId?:number;teachingTask?:string;learningOutcome?:string;recordingDirection?:string;plannedDurationSeconds?:number;audioUrl?:string;durationSeconds?:number;audioSource?:"ai"|"recording";aiAudioUrl?:string;aiDurationSeconds?:number;aiNormalized?:boolean;recordingAudioUrl?:string;recordingDurationSeconds?:number;recordingDenoised?:boolean;recordingNormalized?:boolean;audioOutdated?:boolean};
type VoicePlan={courseThesis:string;sections:Array<{title:string;startPage:number;endPage:number;purpose:string;targetMinutes:number}>};
type Project={id:string;title:string;sourceType:string;sourceFile?:string;status:string;createdAt?:string;slides:Slide[];voicePlan?:VoicePlan;videoUrl?:string;error?:string};
type GenerationProgress={status:"idle"|"running"|"complete"|"error";phase:string;label:string;percent:number;completedPages:number;totalPages:number;currentBatch?:number;totalBatches?:number;currentPage?:number;range?:string;error?:string};
type FormKey="title"|"audience"|"duration"|"style";
function FileDrop({label,hint,file,accept,onChange,icon:Icon}:{label:string;hint:string;file:File|null;accept:string;onChange:(file:File|null)=>void;icon:typeof FileHtml}){return <label className={`upload ${file?"has-file":""}`} onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();onChange(event.dataTransfer.files?.[0]||null)}}><input type="file" accept={accept} onChange={event=>onChange(event.target.files?.[0]||null)}/><span className="upload-icon">{file?<Check size={20} weight="bold"/>:<Icon size={22} weight="duotone"/>}</span><span className="upload-copy"><strong>{label}</strong><span>{file?file.name:hint}</span></span><span className="upload-action">{file?"更换":"选择文件"}</span></label>}
function CourseCard({item,onOpen}:{item:Project;onOpen:(id:string)=>void}){
  const total=item.slides.length,narrated=item.slides.filter(slide=>slide.narration).length,audio=item.slides.filter(slide=>slide.aiAudioUrl||slide.recordingAudioUrl).length;
  const status=item.videoUrl?"成片已完成":audio===total&&total?"音频已完成":audio?`音频 ${audio} / ${total}`:narrated===total&&total?"口播已完成":narrated?`口播 ${narrated} / ${total}`:item.voicePlan?"章节已规划":"课件已解析";
  const progress=item.videoUrl?100:total?Math.round((narrated/total*.55+audio/total*.4)*100):0,code=item.title.match(/^L\d+/)?.[0]||item.sourceType.toUpperCase();
  return <motion.article className="course-card" initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} transition={{duration:.35}}><button type="button" onClick={()=>onOpen(item.id)} aria-label={`打开课程：${item.title}`}><div className="course-card-preview"><img src={`/api/files/${item.id}/thumbnails/slide-01.jpg`} alt={`${item.title} 第一页课件预览`} onError={event=>{event.currentTarget.style.display="none"}}/><span>{code}</span><div className="course-card-open"><ArrowRight size={17} weight="bold"/></div></div><div className="course-card-body"><div className="course-card-title"><div><small>{status}</small><h3>{item.title}</h3></div><strong>{total}<span>页</span></strong></div><div className="course-card-progress" aria-label={`课程制作进度 ${progress}%`}><span style={{width:`${progress}%`}}/></div><div className="course-card-meta"><span>口播 {narrated}/{total}</span><span>音频 {audio}/{total}</span><span>{item.sourceType.toUpperCase()}</span></div></div></button></motion.article>
}
function LoadingState({label,progress}:{label:string;progress:GenerationProgress|null}){return <div className={`loading-state ${progress?"generation-loading":""}`} role="status" aria-live="polite"><div className="loading-line"><span/><span/><span/></div><p>{progress?.label||label}</p>{progress?<><div className="generation-progress-head"><span>{progress.phase==="planning"?"章节规划":progress.phase==="oralizing"?"口语化改写":progress.phase==="audio"?"逐页生成 MP3":progress.phase==="video"?"逐页导出 MP4":progress.phase==="finalizing"?"整理交付":"按章节撰写"}</span><strong>{progress.percent}%</strong></div><div className="generation-progress-track"><span style={{width:`${progress.percent}%`}}/></div><div className="generation-progress-meta"><span>{progress.currentPage?`正在处理第 ${progress.currentPage} 页`:progress.currentBatch?`第 ${progress.currentBatch} / ${progress.totalBatches} 章`:"准备生成"}</span><span>{progress.totalPages?`${progress.completedPages} / ${progress.totalPages} 页完成`:"正在读取课程"}</span></div>{progress.range&&<small>当前处理第 {progress.range} 页，正在依次完成初稿、口语化与时间戳</small>}</>:<small>处理时间取决于课件页数，请保持页面打开</small>}</div>}

function AudioSourceControl({slide,selected,recording,playing,current,positions,onSwitch,onToggle,onSeek}:{slide:Slide;selected:"ai"|"recording";recording:boolean;playing:boolean;current:"ai"|"recording";positions:Record<"ai"|"recording",number>;onSwitch:(source:"ai"|"recording")=>void;onToggle:(source:"ai"|"recording")=>void;onSeek:(source:"ai"|"recording",seconds:number)=>void}){
  const format=(seconds:number)=>`${Math.floor((Number.isFinite(seconds)?seconds:0)/60)}:${String(Math.floor((Number.isFinite(seconds)?seconds:0)%60)).padStart(2,"0")}`;
  const tracks=([{source:"ai" as const,label:"AI 配音",url:slide.aiAudioUrl,duration:slide.aiDurationSeconds||0},{source:"recording" as const,label:slide.recordingDenoised?"本人录音 · 已去噪":"本人录音",url:slide.recordingAudioUrl,duration:slide.recordingDurationSeconds||0}]);
  const track=tracks.find(item=>item.source===selected)!,isPlaying=playing&&current===track.source,position=Math.min(positions[track.source]||0,track.duration||0);
  return <div className="audio-source-control audio-source-simple"><div className="audio-source-tabs" role="radiogroup" aria-label="试听音频来源">{tracks.map(item=><button type="button" role="radio" aria-checked={item.source===selected} className={item.source===selected?"active":""} disabled={recording} onClick={()=>onSwitch(item.source)} key={item.source}>{item.label}</button>)}</div><div className={`audio-player-simple ${!track.url?"unavailable":""}`}><button className="audio-track-play" type="button" aria-label={`${isPlaying?"暂停":"播放"}${track.label}`} disabled={!track.url||recording} onClick={()=>onToggle(track.source)}>{isPlaying?<Pause size={14} weight="fill"/>:<Play size={14} weight="fill"/>}</button><span className="audio-simple-time">{format(position)}</span><input aria-label={`${track.label}播放进度`} type="range" min="0" max={track.duration||0} step="0.1" value={position} disabled={!track.url||recording} onChange={event=>onSeek(track.source,Number(event.target.value))} style={{"--track-progress":`${track.duration?position/track.duration*100:0}%`} as React.CSSProperties}/><span className="audio-simple-time">{track.url?format(track.duration):"—:—"}</span></div></div>
}

export default function Home(){
  const reduceMotion=useReducedMotion();
  const [deck,setDeck]=useState<File|null>(null),[outline,setOutline]=useState<File|null>(null),[project,setProject]=useState<Project|null>(null),[projects,setProjects]=useState<Project[]>([]),[busy,setBusy]=useState(""),[generationProgress,setGenerationProgress]=useState<GenerationProgress|null>(null),[error,setError]=useState(""),[selectedPage,setSelectedPage]=useState(0),[drafts,setDrafts]=useState<Record<number,string>>({}),[batchPanel,setBatchPanel]=useState(false),[optimizeOpen,setOptimizeOpen]=useState(false),[optimizeIntent,setOptimizeIntent]=useState(""),[recording,setRecording]=useState(false),[recordingSeconds,setRecordingSeconds]=useState(0),[globalPlaying,setGlobalPlaying]=useState(false),[exportOpen,setExportOpen]=useState(false),[exportStart,setExportStart]=useState(1),[exportEnd,setExportEnd]=useState(1);
  const deckFrame=useRef<HTMLIFrameElement>(null),thumbnailTimeline=useRef<HTMLDivElement>(null),deckObserver=useRef<MutationObserver|null>(null),audioPlayer=useRef<HTMLAudioElement>(null),pendingPlaySource=useRef<"ai"|"recording"|null>(null),globalPlaybackPending=useRef(false),mediaRecorder=useRef<MediaRecorder|null>(null),recordingChunks=useRef<Blob[]>([]),recordingStream=useRef<MediaStream|null>(null),recordingTimer=useRef<ReturnType<typeof setInterval>|null>(null),recordingPage=useRef<number|null>(null);
  const [audioCurrent,setAudioCurrent]=useState(0),[audioDuration,setAudioDuration]=useState(0),[audioPlaying,setAudioPlaying]=useState(false),[playingSource,setPlayingSource]=useState<"ai"|"recording">("ai"),[selectedAudioTab,setSelectedAudioTab]=useState<"ai"|"recording">("ai"),[audioPositions,setAudioPositions]=useState<Record<"ai"|"recording",number>>({ai:0,recording:0});
  const [form,setForm]=useState({title:"",audience:"高校学生 / 零基础学习者",duration:"40",style:"平静、有经验的大学讲师。先引导观察，再解释概念，避免照读课件。"});
  const update=(key:FormKey,value:string)=>setForm(current=>({...current,[key]:value}));
  const activeSlide=useMemo(()=>project?.slides[selectedPage],[project,selectedPage]);
  const hasActiveNarration=!!(activeSlide?.audioPrompt||activeSlide?.narration);
  useEffect(()=>{fetch("/api/projects/list").then(response=>response.json()).then(data=>Array.isArray(data)&&setProjects(data)).catch(()=>{})},[]);
  useEffect(()=>{const receive=(event:MessageEvent)=>{if(event.source!==deckFrame.current?.contentWindow||event.data?.type!=="mooc-slide-change")return;const index=Number(event.data.index);if(Number.isInteger(index)&&index>=0&&index<(project?.slides.length||0)){if(globalPlaying)globalPlaybackPending.current=true;setSelectedPage(index)}};window.addEventListener("message",receive);return()=>window.removeEventListener("message",receive)},[project?.slides.length,globalPlaying]);
  useEffect(()=>{thumbnailTimeline.current?.querySelector<HTMLElement>(`.thumbnail[data-index="${selectedPage}"]`)?.scrollIntoView({behavior:reduceMotion?"auto":"smooth",block:"nearest",inline:"center"})},[selectedPage,reduceMotion]);
  useEffect(()=>{if(!activeSlide?.audioUrl||pendingPlaySource.current!==(activeSlide.audioSource==="recording"?"recording":"ai"))return;const audio=audioPlayer.current;if(!audio)return;const source=pendingPlaySource.current;pendingPlaySource.current=null;audio.currentTime=audioPositions[source]||0;void audio.play()},[activeSlide?.audioUrl,activeSlide?.audioSource,audioPositions]);
  useEffect(()=>{if(!globalPlaying||!globalPlaybackPending.current)return;const audio=audioPlayer.current;if(!audio||!activeSlide?.audioUrl){globalPlaybackPending.current=false;setGlobalPlaying(false);setError(`第 ${activeSlide?.page||selectedPage+1} 页没有音频，全局播放已暂停。`);return}globalPlaybackPending.current=false;const source=activeSlide.audioSource==="recording"?"recording":"ai";setPlayingSource(source);setSelectedAudioTab(source);audio.currentTime=0;setAudioCurrent(0);void audio.play().catch(()=>{setGlobalPlaying(false);setError("浏览器未能开始播放，请再点击一次全局播放。")})},[activeSlide?.audioUrl,activeSlide?.audioSource,activeSlide?.page,globalPlaying,selectedPage]);
  useEffect(()=>()=>{if(mediaRecorder.current?.state==="recording"){mediaRecorder.current.onstop=null;mediaRecorder.current.stop()}recordingStream.current?.getTracks().forEach(track=>track.stop());if(recordingTimer.current)clearInterval(recordingTimer.current)},[]);
  async function request(url:string,options?:RequestInit){const response=await fetch(url,options),data=await response.json();if(!response.ok)throw new Error(data.error||"处理失败");return data}
  async function createProject(){if(!deck||!outline){setError("请先选择一份课件和一份课纲。");return}setBusy("正在理解课件结构");setError("");try{const body=new FormData();body.append("deck",deck);body.append("outline",outline);Object.entries(form).forEach(([key,value])=>body.append(key,value));const next=await request("/api/projects",{method:"POST",body});setProject(next);setExportStart(1);setExportEnd(next.slides.length||1)}catch(reason){setError(reason instanceof Error?reason.message:"处理失败")}finally{setBusy("")}}
  async function runVideoRange(){if(!project)return;const start=Math.max(1,Math.min(project.slides.length,Math.floor(exportStart))),end=Math.max(1,Math.min(project.slides.length,Math.floor(exportEnd)));if(start>end){setError("导出起始页不能大于结束页。");return}const total=end-start+1;setExportOpen(false);setGlobalPlaying(false);audioPlayer.current?.pause();setBusy(`正在导出第 ${start}–${end} 页视频`);setError("");setGenerationProgress({status:"running",phase:"video",label:`正在准备第 ${start}–${end} 页`,percent:1,completedPages:0,totalPages:total,range:`${start}–${end}`});let timer:ReturnType<typeof setInterval>|undefined;try{const poll=async()=>{try{const response=await fetch(`/api/projects/${project.id}/video/progress`,{cache:"no-store"});if(response.ok)setGenerationProgress(await response.json())}catch{return}};timer=setInterval(poll,900);await poll();const next=await request(`/api/projects/${project.id}/video`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({startPage:start,endPage:end})});setProject(next);if(next.videoUrl){const link=document.createElement("a");link.href=next.videoUrl;link.download=`${project.title}-${start}-${end}.mp4`;document.body.appendChild(link);link.click();link.remove()}}catch(reason){setError(reason instanceof Error?reason.message:"视频导出失败")}finally{if(timer)clearInterval(timer);setBusy("");setGenerationProgress(null)}}
  async function runScriptBatch(mode:"plan"|"chapter",sectionIndex?:number){if(!project)return;const section=sectionIndex===undefined?undefined:project.voicePlan?.sections[sectionIndex];setBusy(mode==="plan"?"正在规划课程章节":`正在生成：${section?.title||"所选章节"}`);setError("");setGenerationProgress({status:"running",phase:mode==="plan"?"planning":"preparing",label:mode==="plan"?"正在根据课纲规划章节":`正在准备：${section?.title||"所选章节"}`,percent:1,completedPages:project.slides.filter(slide=>slide.narration).length,totalPages:project.slides.length});let timer:ReturnType<typeof setInterval>|undefined;try{const poll=async()=>{try{const response=await fetch(`/api/projects/${project.id}/script/progress`,{cache:"no-store"});if(response.ok)setGenerationProgress(await response.json())}catch{return}};timer=setInterval(poll,900);await poll();const next=await request(`/api/projects/${project.id}/script`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode,sectionIndex})});setProject(next);if(section){const index=next.slides.findIndex((slide:Slide)=>slide.page===section.startPage);if(index>=0)setSelectedPage(index)}}catch(reason){setError(reason instanceof Error?reason.message:"处理失败")}finally{if(timer)clearInterval(timer);setBusy("");setGenerationProgress(null)}}
  async function runAudio(mode:"page"|"all",page?:number,text?:string){if(!project)return;setBusy(mode==="page"?`正在生成第 ${page} 页 MP3`:"正在生成逐页 MP3");setError("");setGenerationProgress({status:"running",phase:"audio",label:"正在准备逐页配音",percent:1,completedPages:0,totalPages:mode==="page"?1:project.slides.filter(slide=>slide.narration&&!slide.audioUrl).length});let timer:ReturnType<typeof setInterval>|undefined;try{const poll=async()=>{try{const response=await fetch(`/api/projects/${project.id}/audio/progress`,{cache:"no-store"});if(response.ok)setGenerationProgress(await response.json())}catch{return}};timer=setInterval(poll,900);await poll();setProject(await request(`/api/projects/${project.id}/audio`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode,page,text,force:mode==="page"})}));if(page!==undefined&&text!==undefined)setDrafts(current=>{const next={...current};delete next[page];localStorage.setItem(`voice-drafts:${project.id}`,JSON.stringify(next));return next})}catch(reason){setError(reason instanceof Error?reason.message:"MP3 生成失败")}finally{if(timer)clearInterval(timer);setBusy("");setGenerationProgress(null)}}
  async function optimizeNarration(){if(!project||!activeSlide||!optimizeIntent.trim())return;setBusy("正在按修改意图优化本页口播");setError("");try{const next=await request(`/api/projects/${project.id}/script/optimize`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({page:activeSlide.page,intent:optimizeIntent})});setProject(next);setDrafts(current=>{const updated={...current};delete updated[activeSlide.page];localStorage.setItem(`voice-drafts:${project.id}`,JSON.stringify(updated));return updated});setOptimizeIntent("");setOptimizeOpen(false)}catch(reason){setError(reason instanceof Error?reason.message:"口播优化失败")}finally{setBusy("")}}
  async function uploadRecording(blob:Blob,page:number){if(!project)return;setBusy("正在去噪并保存录音");setError("");try{const body=new FormData();body.append("page",String(page));body.append("audio",blob,`page-${page}.webm`);setProject(await request(`/api/projects/${project.id}/audio/recording`,{method:"POST",body}))}catch(reason){setError(reason instanceof Error?reason.message:"录音去噪失败")}finally{setBusy("")}}
  async function switchAudioSource(source:"ai"|"recording"){if(!project||!activeSlide||source===activeSlide.audioSource)return;setError("");try{setProject(await request(`/api/projects/${project.id}/audio/source`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({page:activeSlide.page,source})}))}catch(reason){setError(reason instanceof Error?reason.message:"音频切换失败")}}
  async function selectAudioTab(source:"ai"|"recording"){if(!activeSlide||recording)return;setGlobalPlaying(false);audioPlayer.current?.pause();setAudioPlaying(false);setSelectedAudioTab(source);const exists=source==="ai"?activeSlide.aiAudioUrl:activeSlide.recordingAudioUrl;if(exists)await switchAudioSource(source)}
  async function startRecording(){if(!activeSlide)return;setError("");setGlobalPlaying(false);try{audioPlayer.current?.pause();const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}}),recorder=new MediaRecorder(stream);recordingStream.current=stream;mediaRecorder.current=recorder;recordingChunks.current=[];recordingPage.current=activeSlide.page;setRecordingSeconds(0);recorder.ondataavailable=event=>{if(event.data.size)recordingChunks.current.push(event.data)};recorder.onstop=()=>{const blob=new Blob(recordingChunks.current,{type:recorder.mimeType||"audio/webm"}),page=recordingPage.current;recordingStream.current?.getTracks().forEach(track=>track.stop());recordingStream.current=null;if(recordingTimer.current)clearInterval(recordingTimer.current);recordingTimer.current=null;setRecording(false);if(page!==null&&blob.size)uploadRecording(blob,page)};recorder.start(500);setRecording(true);recordingTimer.current=setInterval(()=>setRecordingSeconds(value=>value+1),1000)}catch(reason){setError(reason instanceof Error?`无法开始录音：${reason.message}`:"无法使用麦克风，请检查浏览器权限。")}}
  function stopRecording(){if(mediaRecorder.current?.state==="recording")mediaRecorder.current.stop()}
  function resetProject(){audioPlayer.current?.pause();setGlobalPlaying(false);setExportOpen(false);setProject(null);setSelectedPage(0);setDrafts({});setError("")}
  async function openProject(id:string){setBusy("正在打开课程");try{const next=await request(`/api/projects/${id}`);setProject(next);setSelectedPage(0);setGlobalPlaying(false);setExportStart(1);setExportEnd(next.slides.length||1);try{setDrafts(JSON.parse(localStorage.getItem(`voice-drafts:${id}`)||"{}"))}catch{setDrafts({})}}catch(reason){setError(reason instanceof Error?reason.message:"课程打开失败")}finally{setBusy("")}}
  function editDraft(page:number,value:string){setDrafts(current=>{const next={...current,[page]:value};if(project)localStorage.setItem(`voice-drafts:${project.id}`,JSON.stringify(next));return next})}
  function selectPage(index:number){if(recording||!project||index<0||index>=project.slides.length)return;if(globalPlaying)globalPlaybackPending.current=true;audioPlayer.current?.pause();setAudioPlaying(false);setAudioCurrent(0);setAudioPositions({ai:0,recording:0});setSelectedAudioTab(project.slides[index]?.audioSource==="recording"?"recording":"ai");setAudioDuration(project.slides[index]?.durationSeconds||0);setOptimizeOpen(false);setOptimizeIntent("");setSelectedPage(index);const frame=deckFrame.current?.contentWindow as (Window&{show?:(index:number)=>void})|null;frame?.show?.(index)}
  async function toggleTrack(source:"ai"|"recording"){const audio=audioPlayer.current;if(!audio||!activeSlide)return;setGlobalPlaying(false);if(source!==activeSlide.audioSource){audio.pause();pendingPlaySource.current=source;setPlayingSource(source);await switchAudioSource(source);return}setPlayingSource(source);audio.currentTime=audioPositions[source]||0;if(audio.paused)await audio.play();else audio.pause()}
  function seekTrack(source:"ai"|"recording",value:number){setAudioPositions(current=>({...current,[source]:value}));if(source!==activeSlide?.audioSource)return;const audio=audioPlayer.current;if(!audio)return;audio.currentTime=value;setAudioCurrent(value)}
  async function toggleAudio(){const audio=audioPlayer.current;if(!audio||!activeSlide?.audioUrl)return;setGlobalPlaying(false);setPlayingSource(activeSlide.audioSource==="recording"?"recording":"ai");if(audio.paused)await audio.play();else audio.pause()}
  function seekAudio(value:number){const audio=audioPlayer.current;if(!audio)return;audio.currentTime=value;setAudioCurrent(value);const source=activeSlide?.audioSource==="recording"?"recording":"ai";setAudioPositions(current=>({...current,[source]:value}))}
  async function toggleGlobalPlayback(){const audio=audioPlayer.current;if(!project||recording)return;if(globalPlaying){setGlobalPlaying(false);audio?.pause();return}if(!activeSlide?.audioUrl){setError(`第 ${activeSlide?.page||selectedPage+1} 页没有音频，无法开始全局播放。`);return}setError("");setGlobalPlaying(true);setPlayingSource(activeSlide.audioSource==="recording"?"recording":"ai");if(audio){try{await audio.play()}catch{setGlobalPlaying(false);setError("浏览器未能开始播放，请再点击一次。")}}}
  function handleAudioEnded(){setAudioPlaying(false);if(!globalPlaying||!project)return;if(selectedPage>=project.slides.length-1){setGlobalPlaying(false);return}const next=project.slides[selectedPage+1];if(!next.audioUrl){setGlobalPlaying(false);setError(`第 ${next.page} 页没有音频，全局播放已暂停。`);return}globalPlaybackPending.current=true;selectPage(selectedPage+1)}
  const formatAudioTime=(seconds:number)=>`${Math.floor((Number.isFinite(seconds)?seconds:0)/60)}:${String(Math.floor((Number.isFinite(seconds)?seconds:0)%60)).padStart(2,"0")}`;
  function connectDeckPageSync(){const frame=deckFrame.current,win=frame?.contentWindow;if(!win)return;const sections=[...win.document.querySelectorAll<HTMLElement>("section.slide, section")];if(!sections.length)return;const notify=()=>{const index=sections.findIndex(section=>section.classList.contains("active")||(win.getComputedStyle(section).display!=="none"&&win.getComputedStyle(section).visibility!=="hidden"));if(index>=0)win.parent.postMessage({type:"mooc-slide-change",index},win.location.origin)};deckObserver.current?.disconnect();deckObserver.current=new MutationObserver(notify);sections.forEach(section=>deckObserver.current?.observe(section,{attributes:true,attributeFilter:["class","style","hidden"]}));win.addEventListener("hashchange",notify);notify();selectPage(selectedPage)}
  const primaryAction=project&&!project.slides.every(slide=>slide.narration)?{label:"分批生成口播",action:()=>setBatchPanel(true)}:null;
  const narratedCount=project?.slides.filter(slide=>slide.narration).length||0,audioCount=project?.slides.filter(slide=>slide.aiAudioUrl).length||0;
  const activeOriginal=activeSlide?.audioPrompt??activeSlide?.narration??"",activeDraft=activeSlide?drafts[activeSlide.page]:undefined,activeEdited=activeDraft!==undefined&&activeDraft!==activeOriginal;
  const needsAudioUpdate=activeEdited||!!activeSlide?.audioOutdated;

  return <main className={`page-shell ${project?"project-mode":"home-mode"}`} id="content">
    <a href="#content" className="skip-link">跳到主要内容</a>
    {!project&&<div className="home-content">
      <motion.section className="home-create" initial={reduceMotion?false:{opacity:0,y:16}} animate={{opacity:1,y:0}} transition={{duration:.5,delay:.06,ease:[.2,.8,.2,1]}} aria-label="新建课程"><div className="home-upload-grid"><FileDrop label="上传课件" hint="HTML、ZIP、PDF 或 PPTX" file={deck} accept=".html,.htm,.pdf,.pptx,.zip" onChange={setDeck} icon={FileHtml}/><FileDrop label="上传课纲" hint="Markdown、TXT 或 DOCX" file={outline} accept=".md,.txt,.docx" onChange={setOutline} icon={FileText}/></div><details className="course-options"><summary><span>课程设置</span><small>选填，系统已有推荐值</small><CaretDown size={15} weight="bold"/></summary><div className="course-options-grid"><div className="field option-title"><label htmlFor="course-title">课程名称 <span>可自动识别</span></label><input id="course-title" value={form.title} onChange={event=>update("title",event.target.value)} placeholder="留空后从课件封面识别"/></div><div className="field option-time"><label htmlFor="duration">目标时长</label><div className="input-suffix"><input id="duration" type="number" min="3" max="180" value={form.duration} onChange={event=>update("duration",event.target.value)}/><span>分钟</span></div></div><div className="field"><label htmlFor="audience">学习者</label><input id="audience" value={form.audience} onChange={event=>update("audience",event.target.value)}/></div><div className="field option-style"><label htmlFor="style">讲述方式</label><textarea id="style" value={form.style} onChange={event=>update("style",event.target.value)}/></div></div></details><footer className="home-create-footer"><button className="primary" disabled={!!busy||!deck||!outline} onClick={createProject}><Sparkle size={17} weight="fill"/>创建课程<ArrowRight size={15} weight="bold"/></button></footer>{error&&<div className="error" role="alert"><strong>课程没有创建成功</strong><span>{error}</span></div>}</motion.section>
      <section className="course-collection" aria-labelledby="course-library-title"><header><div><p>课程库</p><h2 id="course-library-title">继续制作</h2></div><span>{projects.length?`${projects.length} 门课程`:`还没有课程`}</span></header>{projects.length?<div className="course-grid">{projects.map(item=><CourseCard item={item} onOpen={openProject} key={item.id}/>)}</div>:<div className="course-empty"><BookOpenText size={24} weight="duotone"/><div><strong>第一门课程会出现在这里</strong><span>上传课件与课纲后，可以随时返回继续编辑。</span></div></div>}</section>
      <footer className="home-footer"><span>MOOC Studio Agent</span><p>课件解析、口播、配音与录制均在当前工作区完成</p></footer>
    </div>}

    <AnimatePresence mode="wait">{busy&&<motion.section className="stage-screen" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><LoadingState label={busy} progress={generationProgress}/></motion.section>}</AnimatePresence>

    {project&&!busy&&<section className="project-stage">
      <header className="editor-topbar"><button className="editor-back" onClick={resetProject}><CaretLeft size={14} weight="bold"/>课程列表</button><span className="editor-badge">{project.title.match(/^L\d+/)?.[0]||"课程"}</span><h1>{project.title.replace(/^L\d+\s*[·・]?\s*/,"")}</h1><span className="editor-status">口播预览编辑器 · {project.slides.length} 页 · {audioCount?`已生成 ${audioCount} 页 MP3`:"尚未生成语音"}</span><div className="editor-action">{primaryAction&&<button className="primary" onClick={primaryAction.action}><Sparkle size={17} weight="fill"/>{primaryAction.label}</button>}{narratedCount>audioCount&&<button className="primary audio-action" onClick={()=>runAudio("all")}><Waveform size={17} weight="fill"/>生成 {narratedCount-audioCount} 页 MP3</button>}{project.videoUrl&&<a className="primary" href={project.videoUrl} download><DownloadSimple size={18} weight="bold"/>下载视频</a>}</div></header>
      <AnimatePresence>{batchPanel&&<motion.div className="batch-overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setBatchPanel(false)}><motion.aside className="batch-drawer" initial={{x:420}} animate={{x:0}} exit={{x:420}} transition={{duration:.24,ease:[.2,.8,.2,1]}} onClick={event=>event.stopPropagation()} aria-label="分批生成口播"><header><div><span>分批生成</span><h2>先试一章，再继续</h2></div><button aria-label="关闭" onClick={()=>setBatchPanel(false)}><X size={18}/></button></header>{!project.voicePlan?<div className="batch-empty"><BookOpenText size={28} weight="duotone"/><strong>先让 Agent 划分章节</strong><p>只读取课纲并生成章节规划，不写口播。完成后您可以任选一章单独测试。</p><button className="primary" onClick={()=>{setBatchPanel(false);runScriptBatch("plan")}}><Sparkle size={16} weight="fill"/>生成章节规划</button></div>:<><div className="batch-summary"><p>{project.voicePlan.courseThesis}</p><span>{project.voicePlan.sections.length} 个章节 · 已完成 {project.slides.filter(slide=>slide.narration).length} / {project.slides.length} 页</span></div><div className="batch-list">{project.voicePlan.sections.map((section,index)=>{const pages=project.slides.filter(slide=>slide.page>=section.startPage&&slide.page<=section.endPage),done=pages.length>0&&pages.every(slide=>slide.narration);return <article className={done?"done":""} key={`${section.startPage}-${section.endPage}`}><div className="batch-number">{String(index+1).padStart(2,"0")}</div><div className="batch-copy"><strong>{section.title}</strong><span>第 {section.startPage}–{section.endPage} 页 · 约 {section.targetMinutes} 分钟</span><p>{section.purpose}</p></div>{done?<button className="batch-done" onClick={()=>{setBatchPanel(false);selectPage(project.slides.findIndex(slide=>slide.page===section.startPage))}}><Check size={15} weight="bold"/>查看</button>:<button className="batch-generate" onClick={()=>{setBatchPanel(false);runScriptBatch("chapter",index)}}>生成本章<CaretRight size={14} weight="bold"/></button>}</article>})}</div><button className="replan" onClick={()=>{setBatchPanel(false);runScriptBatch("plan")}}>重新规划章节 <CaretDown size={13}/></button></>}</motion.aside></motion.div>}</AnimatePresence>
      {error&&<div className="project-error error" role="alert"><strong>这一步没有完成</strong><span>{error}</span></div>}
      <section className="preview-editor">
        <div className="preview-stage"><div className="deck-canvas"><div className="canvas-label"><span>课程画面</span><strong>{String(selectedPage+1).padStart(2,"0")} / {String(project.slides.length).padStart(2,"0")}</strong></div>{project.sourceType==="html"?<iframe ref={deckFrame} title="课程课件预览" src={`/api/deck/${project.id}/${encodeURIComponent(project.sourceFile||"课件.html")}`} onLoad={connectDeckPageSync}/>:<div className="deck-unavailable"><FileHtml size={35} weight="duotone"/><span>当前格式暂不支持动态课件预览</span></div>}<audio key={`${activeSlide?.page}-${activeSlide?.audioUrl||"silent"}`} ref={audioPlayer} src={activeSlide?.audioUrl} preload="metadata" onLoadStart={()=>{setAudioPlaying(false);setAudioCurrent(0);setAudioDuration(activeSlide?.durationSeconds||0)}} onTimeUpdate={event=>{const time=event.currentTarget.currentTime;setAudioCurrent(time);const source=activeSlide?.audioSource==="recording"?"recording":"ai";setAudioPositions(current=>({...current,[source]:time}))}} onLoadedMetadata={event=>setAudioDuration(event.currentTarget.duration)} onPlay={()=>setAudioPlaying(true)} onPause={()=>setAudioPlaying(false)} onEnded={handleAudioEnded}/><div className="audio-timeline"><button aria-label={audioPlaying?"暂停本页音频":"播放本页音频"} disabled={!activeSlide?.audioUrl} onClick={toggleAudio}>{audioPlaying?<Pause size={15} weight="fill"/>:<Play size={15} weight="fill"/>}</button><span className="audio-time">{formatAudioTime(audioCurrent)}</span><input aria-label="本页音频播放进度" type="range" min="0" max={audioDuration||0} step="0.1" value={Math.min(audioCurrent,audioDuration||0)} disabled={!activeSlide?.audioUrl} onChange={event=>seekAudio(Number(event.target.value))} style={{"--audio-progress":`${audioDuration?audioCurrent/audioDuration*100:0}%`} as React.CSSProperties}/><span className="audio-time">{activeSlide?.audioUrl?formatAudioTime(audioDuration):"—:—"}</span></div><div className="page-nav"><button aria-label="上一页" disabled={selectedPage===0} onClick={()=>selectPage(selectedPage-1)}><CaretLeft size={17} weight="bold"/></button><button aria-label="下一页" disabled={selectedPage===project.slides.length-1} onClick={()=>selectPage(selectedPage+1)}><CaretRight size={17} weight="bold"/></button></div></div></div>
        <aside className="script-panel"><div className="script-editor-wrap"><textarea aria-label="完整音频 Prompt 编辑区" disabled={!hasActiveNarration||recording} placeholder={hasActiveNarration?"":"点击右上角“生成逐页口播”后，本页口播稿会显示在这里。"} value={hasActiveNarration?(drafts[activeSlide?.page||0]??activeSlide?.audioPrompt??activeSlide?.narration??""):""} onChange={event=>activeSlide&&hasActiveNarration&&editDraft(activeSlide.page,event.target.value)}/><button className={`optimize-icon ${optimizeOpen?"active":""}`} aria-label="优化本页口播" disabled={!hasActiveNarration||recording} onClick={()=>setOptimizeOpen(value=>!value)}><Sparkle size={15} weight="duotone"/><span>优化</span></button></div><div className="script-panel-footer">{optimizeOpen&&<div className="optimize-box"><label htmlFor="optimize-intent">希望怎样调整本页口播？</label><textarea id="optimize-intent" value={optimizeIntent} onChange={event=>setOptimizeIntent(event.target.value)} placeholder="例如：压缩到20秒，更口语一些，不要使用反问。"/><div><button onClick={()=>{setOptimizeOpen(false);setOptimizeIntent("")}}>取消</button><button className="optimize-submit" disabled={!optimizeIntent.trim()} onClick={optimizeNarration}><Sparkle size={14} weight="fill"/>开始优化</button></div></div>}{activeSlide&&hasActiveNarration&&<AudioSourceControl slide={activeSlide} selected={selectedAudioTab} recording={recording} playing={audioPlaying} current={playingSource} positions={audioPositions} onSwitch={selectAudioTab} onToggle={toggleTrack} onSeek={seekTrack}/>}<div className="script-buttons script-buttons-single">{selectedAudioTab==="recording"?<button className={`preview-primary ${recording?"recording":""}`} disabled={!hasActiveNarration} onClick={recording?stopRecording:startRecording}>{recording?`${formatAudioTime(recordingSeconds)} · 停止录音`:activeSlide?.recordingAudioUrl?"重新录音":"录音"}</button>:(!activeSlide?.aiAudioUrl||needsAudioUpdate?<button className="preview-primary" disabled={!hasActiveNarration||recording} onClick={()=>activeSlide&&runAudio("page",activeSlide.page,activeEdited?activeDraft:undefined)}><Waveform size={16} weight="fill"/>{needsAudioUpdate?"更新 AI 配音":"生成 AI 配音"}</button>:<div className="audio-control-note"><Check size={14} weight="bold"/>请使用上方对应音轨的播放器试听</div>)}</div></div></aside>
        <div className="timeline-zone"><div className="timeline-toolbar"><div className="global-playback"><button className={globalPlaying?"active":""} type="button" disabled={!activeSlide?.audioUrl||recording} onClick={toggleGlobalPlayback}>{globalPlaying?<Pause size={14} weight="fill"/>:<Play size={14} weight="fill"/>}<span>{globalPlaying?"暂停播放":"全局播放"}</span></button><small>{globalPlaying?`正在播放第 ${selectedPage+1} / ${project.slides.length} 页`:`从当前第 ${selectedPage+1} 页开始`}</small></div><div className="export-range-control"><button className="export-range-trigger" type="button" disabled={project.sourceType!=="html"} onClick={()=>{setExportStart(selectedPage+1);setExportEnd(project.slides.length);setExportOpen(value=>!value)}}><FilmSlate size={15} weight="duotone"/><span>录制导出</span><CaretDown size={12} weight="bold"/></button>{exportOpen&&<div className="export-range-popover" role="dialog" aria-label="选择视频导出范围"><header><div><strong>选择导出范围</strong><span>每页分别录制，再合成为一个 MP4</span></div><button type="button" aria-label="关闭导出范围" onClick={()=>setExportOpen(false)}><X size={15}/></button></header><div className="export-range-fields"><label><span>起始页</span><input type="number" min="1" max={project.slides.length} value={exportStart} onChange={event=>setExportStart(Number(event.target.value))}/></label><span>至</span><label><span>结束页</span><input type="number" min="1" max={project.slides.length} value={exportEnd} onChange={event=>setExportEnd(Number(event.target.value))}/></label></div><div className="export-range-shortcuts"><button type="button" onClick={()=>{setExportStart(1);setExportEnd(project.slides.length)}}>全部页</button><button type="button" onClick={()=>{setExportStart(selectedPage+1);setExportEnd(project.slides.length)}}>当前页到结尾</button></div><button className="export-range-submit" type="button" disabled={exportStart<1||exportEnd>project.slides.length||exportStart>exportEnd} onClick={runVideoRange}><FilmSlate size={15} weight="fill"/>导出第 {exportStart}–{exportEnd} 页</button></div>}</div></div><div className="thumbnail-timeline" ref={thumbnailTimeline}>{project.slides.map((slide,index)=><button className={`thumbnail ${index===selectedPage?"active":""}`} data-index={index} onClick={()=>selectPage(index)} title={slide.title} key={slide.page}><img src={`/api/files/${project.id}/thumbnails/slide-${String(slide.page).padStart(2,"0")}.jpg`} alt={`第 ${slide.page} 页：${slide.title}`} onError={event=>{event.currentTarget.style.display="none"}}/><b>{slide.page}</b></button>)}</div></div>
      </section>
    </section>}
  </main>
}
